#!/usr/bin/env python3

import sys
import os

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name")
    
    # Get screen name
    screen_name = sys.argv[1].strip("@")
    
    # Obtain 50 tweets
    tweets = get_user_timeline(screen_name, count = 50)
    if tweets == None:
        sys.exit("Error: Unable to get tweets")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
      
    # analyze word
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))
            
if __name__ == "__main__":
    main()